name: Stock Options Collection

on:
  schedule:
    # Run daily at market open (8:35 AM CST / 2:35 PM UTC) and every 2 hours until market close (3:35 PM CST / 9:35 PM UTC)
    - cron: '35 14,16,18,20,22 * * 1-5'
  workflow_dispatch:
    inputs:
      config_id:
        description: 'Specific configuration ID to run (optional)'
        required: false
        type: string

env:
  OPTIONS_API_KEY: ${{ secrets.OPTIONS_API_KEY }}

jobs:
  stock-options:
    runs-on: ubuntu-latest
    name: Stock Options Collection
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run stock options collection
      run: npm run cron:stock
      
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Stock Options Collection Failed',
            body: 'The stock options collection job failed. Please check the logs.',
            labels: ['bug', 'options', 'stock']
          })
